[package]
name = "next-transform-page-config"
version = "0.1.0"
description = "SWC transform to support PageConfig"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[dependencies]
chrono = { workspace = true }

turbo-binding = { workspace = true, features = [
  "__swc_core",
] }

[dev-dependencies]
